#+ summary: Returns the track names of the MIDI file of the Ghostbusters theme
#+ endpoint: https://raw.githubusercontent.com/albertmeronyo/lodapi/master/ghostbusters.ttl
#+ mime: text/turtle
#+ tags:
#+   - RDF dump
#+ defaults:
#+   - type: mid:Track

PREFIX mid: <http://example.org/midi/>

SELECT ?s WHERE {
    ?s a ?_type_iri .
}